### ISSUE TITLE
Filter and Pagination

### ISSUE THREAD

**Issue by axelrivera** [SoPR/sopr-platform#12]
This thing is going to need pagination and filters soon!!

**Comment by omarramos** [comment]
I can work on it, do we want infinite scrolling or standard pagination?

**Comment by gcollazo** [comment]
Standard pagination is better for SEO and infinite scrolling better for UX. I prefer standard pagination. My 2 cents.

**Comment by jonahoffline** [comment]
I agree with Giovanni, standard pagination.

**Comment by jpadilla** [comment]
How about we separate filters/search from pagination?

Edit: standard pagination :+1:

**Comment by axelrivera** [comment]
Standard pagination is good.

With filter at a minimum the user should be able to filter by hacker, developer, entrepreneur, etc.  Maybe a search??

**Comment by ryanoliver** [comment]
+1 to Standard pagination

on filter we could start by filtering by role

**Comment by jonahoffline** [comment]
I had a mock idea in Blimp a few weeks ago. Here is the link ![screen](https://s3.amazonaws.com/com.getblimp.uploads/uploads/users/jonah%40pixelhipsters.com/98288af2-2f20-4260-9656-fa01b1036903/SoPR-Platform-UserSortSearch.png)

**Comment by ryanoliver** [comment]
Jonah do you have de omnigraffle file ?

## 

Ryan Oliver
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by jonahoffline** [comment]
Yes, let me upload it to Blimp.

**Comment by omarramos** [comment]
Here is the initial paging implementation, it needs some design love.

https://github.com/jpadilla/sopr-platform/pull/13

**Comment by jonahoffline** [comment]
Ryan, check the file section or download from here:

[SoPR-graffle](https://s3.amazonaws.com/com.getblimp.uploads/uploads/users/jonah%40pixelhipsters.com/6968dfe6-076e-4514-8900-fc9f615421bc/SoPR-Platform.graffle.zip)

**Comment by axelrivera** [comment]
That design is cool.  It should be "Filter by" instead of "Sort" tough.

**Comment by jonahoffline** [comment]
Yeah, 'Filter by' sounds much better!

**Comment by jonahoffline** [comment]
Closing this issue. Pagination has been added.
