### ISSUE TITLE
New RVM Behavior With .ruby-version and .ruby-gemset

### ISSUE THREAD

**Issue by jpadilla** [SoPR/sopr-platform#2]
Ahora mismo tenemos .rvmrc y .ruby-gemset/.ruby-version. Estos últimos creo que son lo nuevo pa usarse con RVM. Leí esto y pensé que talvez quieras update. Si no maybe debemos de sacar estos files del repo y ponerlos en el .gitignore pa evitar problemas.

http://rayhightower.com/blog/2013/04/18/new-rvm-behavior-ruby-version-ruby-gemset/

**Comment by ryanoliver** [comment]
Nice no sabia esto ok awesome le doy un update y nos quedamos con lo nuevo.
