### ISSUE TITLE
Travis CI Test Build Error

### ISSUE THREAD

**Issue by ryanoliver** [SoPR/sopr-platform#21]
@jonahoffline  cree un branch nuevo con el feature de events estoy teniendo un error en el build de events.

**Comment by jonahoffline** [comment]
@r23712 le doy un check cuando llegue a casa esta noche.

**Comment by jonahoffline** [comment]
I'm working on this now.

**Comment by jonahoffline** [comment]
@r23712 @jpadilla  Fixed.
El problema era que al usar group_by en el controller de Events, el te devuelve un Hash / ActiveRecord::OrderedHash. Eso funciona nice pero al hacerle un stub en el spec view para probarlo solo estabas dandole la data normal como un ActiveRecord::Relation. 

Como el stub es un fake ass object y no tenia el group_by no te sale jamas. Tuve que hacer el group_by en el mismo view, lo cual es un poco puerco pero por ahora resuelve. Tan pronto encuentre una mejor solución le hacemos un refactoring. Cheers :cake:

**Comment by jonahoffline** [comment]
[![Build Status](https://travis-ci.org/jpadilla/sopr-platform.png?branch=events)](https://travis-ci.org/jpadilla/sopr-platform)
https://travis-ci.org/jpadilla/sopr-platform/builds/11749454

**Comment by ryanoliver** [comment]
Awesome @jonahoffline
