### ISSUE TITLE
iCalendar feed date in our timezone

### ISSUE THREAD

**Issue by jpadilla** [SoPR/sopr-platform#26]
The dates we are setting in the admin are thought in our local time but are stored in UTC. I tried converting them to the correct zone `in_time_zone` but that also changes are time by the offset of the timezone. What I wanted to achieve was just changing the timezone offset without changing the actual time. Any help with this?

Update:
I think we also have to do the same for  the date/times on the RSS feed

**Comment by jonahoffline** [comment]
@jpadilla I'll give it a look later on Today!

**Comment by jonahoffline** [comment]
I was trying to find a way around this but it fucks up the offset by one hour.

**Comment by jpadilla** [comment]
@jonahoffline think it's something that ri_cal gem is doing? I'm thinking I can use do a .icsbuilder instead like I did for RSS. Thoughts?
