### ISSUE TITLE
Office Hours

### ISSUE THREAD

**Issue by gcollazo** [SoPR/sopr-platform#27]
Voy a hacer algo que odio que es sugerir un feature y luego no someter código, pero de todos modos aquí va.

Creo que el "killer feature" de este site debe ser publicar y coordinar reuniones entre miembros de la comunidad en y fuera de PR. Ya tenemos los eventos que pasan todas las semanas pero estos no son suficientes. Además las interacción están limitadas a las personas que están ahí ese día.

sopr-plaftform podría resolver este issue para la comunidad y convertirse en una herramienta super útil.

La idea es esta:
- Cada usuario publica sus horas de oficina como parte de su perfil
- Cualquier otro usuario registrado puede reservar un espacio
- Las reuniones serán via telefono, skype, google hangout o en persona por lo que el app debe estar "aware" de esto para pedir la información relevante
- Añadir un paso al registro que le pida a los usuarios entrar sus horas de oficina y no listar horas sea como algo negativo. Lo que me viene a la mente son dos botones en el form uno que dice "List my hours" y otro "I don't want to help the community by posting office hours". :smile: 

La meta es que todo el mundo liste por los menos 1 hora a la semana dividido en 2 espacios de 30 minutos. De esta forma tendremos mucho inventario que podemos mover.

Una vez se tenga esto se me ocurren mil ideas para promocionar que las persona hagan "booking" de las horas y de showcase en un blog o algo las historias de éxito.

Suena a mucho trabajo ¿Que creen?

**Comment by jonahoffline** [comment]
Tremenda idea, I'm game for this :+1:

**Comment by gcollazo** [comment]
Shameless plug: Esta idea terminó convietiendose en http://1hora.org y el proyecto http://github.com/SoPR/horas.
