### ISSUE TITLE
Incorrect rendering on Firefox 24.0 OSX

### ISSUE THREAD

**Issue by ricardoalcocer** [SoPR/sopr-platform#29]
See screenshot: http://awesomescreenshot.com/0d71wfmd3f

**Comment by jonahoffline** [comment]
Hi @ricardoalcocer, thanks for your submission. 
I just tried Firefox 24.0 but rendering seems fine (running Mountain Lion). Are you on Mavericks?

**Comment by ricardoalcocer** [comment]
10.8.5.  I see the problem now.  It has to do with media queries...I never maximize my browser. Scale down the browser and you'll see it.  Not a huge deal I guess.  The button is white on white though.
