### ISSUE TITLE
SendGrid Credit Limit Exhausted

### ISSUE THREAD

**Issue by jpadilla** [SoPR/sopr-platform#35]
Recibí este email de SendGrid hace unos días. Usé mi cuenta personal. Que hacemos? Puedo abrir una cuenta nueva específicamente para esto and ride out los credits de esa cuenta nueva.

> Today, your account under username jpadilla has used all of its credits.
> 
> You have reached your credit limit and you will not be able to send email until your credits renew or you upgrade your account. We recommend that you upgrade your account in order to continue to send email worry free!

**Comment by gcollazo** [comment]
Mandrill tiene [12,000 al mes gratis](http://mandrill.com/pricing/). Es lo que voy a usar para sopr/horas.

**Comment by jpadilla** [comment]
Configured to use a new free Mandrill account.
