### ISSUE TITLE
Style pagination on People section

### ISSUE THREAD

**Issue by jpadilla** [SoPR/sopr-platform#36]

**Comment by jonahoffline** [comment]
@jpadilla I just noticed this old issue. The current pagination looks fugly. 
If you provide an example of the desired style I will happy implement it.

**Comment by jpadilla** [comment]
@jonahoffline think we can probably go with whatever is done in https://1hora.org/search/ which I think is Bootstrap's default.

**Comment by jonahoffline** [comment]
Perfect, I'll change the current pagination theme as soon as I have a chance Tomorrow.

**Comment by jpadilla** [comment]
:+1: thanks!
