### ISSUE TITLE
Dependency Alerts

### ISSUE THREAD

**Issue by jpadilla** [SoPR/sopr-platform#38]
Este proyecto tiene various pending dependency alerts relacionados a vulnerabilities de seguridad relacionados a Rails y a ActiveRecord. Any takers en tratar de arreglar esto?

Más detalles en: https://gemnasium.com/jpadilla/sopr-platform/alerts

**Comment by jonahoffline** [comment]
I'll work on it Today.

**Comment by jpadilla** [comment]
You get :100: more karma points! Si necesitas algo, me avisas.
