### ISSUE TITLE
Header Font in About Page

### ISSUE THREAD

**Issue by jomajoma** [SoPR/sopr-platform#39]
El "font" que utilizan en el header "Do What You Love"  (montez, cursive), es diferente al que usan en todas las demás páginas. 

![image](https://cloud.githubusercontent.com/assets/7673608/3981431/3a29d9f0-286e-11e4-8cb2-08ce69bb1fcc.png)

Luce 'raro'. Sugiero utilicen el mismo "family font" que en los demás "pages" 'Open Sans', Helvetica, Arial, sans-serif.

**Comment by jonahoffline** [comment]
Uiiiiiiii, Comic Sans :no_good: El font es "montez", pero tienes razón.
![screen shot 2014-08-20 at 9 38 08 am](https://cloud.githubusercontent.com/assets/1783738/3981564/569ba1bc-286f-11e4-8f82-378bb9ef1a1c.png)

Will work on this.

**Comment by jpadilla** [comment]
@jonahoffline que crees si hacemos que el font-family de ese header sea: `montez, cursive, 'Open Sans', Helvetica, Arial, sans-serif;`.

**Comment by jonahoffline** [comment]
@jpadilla :+1:
