### ISSUE TITLE
Outdated Travis CI Settings

### ISSUE THREAD

**Issue by jonahoffline** [SoPR/sopr-platform#40]
The repository's current configuration for Travis CI is outdated. 
@jpadilla I'd love to make the changes myself, but lack the admin access to do so :wink:

**Comment by jpadilla** [comment]
Al parecer yo tampoco.

Ping @gcollazo

**Comment by gcollazo** [comment]
Sorry, you are now all admins

**Comment by jonahoffline** [comment]
@gcollazo thanks!
