### ISSUE TITLE
Missing Icon Fonts

### ISSUE THREAD

**Issue by gcollazo** [SoPR/sopr-platform#42]
![](https://s3.amazonaws.com/f.cl.ly/items/413P1I173P3c0h1Z3H1k/Image%202014-09-08%20at%207.41.39%20PM.png)

**Comment by jonahoffline** [comment]
Looks like a CORS issue, can you add the header in the S3 Bucket configuration?

![screen shot 2014-09-09 at 11 56 58 am](https://cloud.githubusercontent.com/assets/1783738/4204840/b86ff8d6-383a-11e4-83b7-92c16a7fe401.png)

**Comment by gcollazo** [comment]
No tengo acceso a ese bucket maybe @r23712 o @jpadilla pueden.

**Comment by jonahoffline** [comment]
@jpadilla :+1: thanks

**Comment by ryanoliver** [comment]
Thanks for fixing this 

@gcollazo @jpadilla @jonahoffline

**Comment by jonahoffline** [comment]
@r23712 np dude!
