### ISSUE TITLE
Can't save user after changing admin status

### ISSUE THREAD

**Issue by gcollazo** [SoPR/sopr-platform#43]
![](https://s3.amazonaws.com/f.cl.ly/items/1I1O1O3M0R2X0d0W3x3d/Screen%20Recording%202014-09-08%20at%2007.40%20PM.gif)

**Comment by jonahoffline** [comment]
I'll work on it.

**Comment by jonahoffline** [comment]
Fixed with 45d95a16e1391c4da0ac76e3b2176eef7e7c985b
@gcollazo changes have been deployed :smile:

**Comment by gcollazo** [comment]
![slowclap](https://cloud.githubusercontent.com/assets/61048/4204695/9ac4450e-3839-11e4-87b6-e8fd5f64218f.gif)

**Comment by marcospolanco** [comment]
El comentario de Gio esta...amazing. Yeah, esto me ayuda personalmente, asi que gracias Jonah!

**Comment by jonahoffline** [comment]
@gcollazo jajajaja 
@marcospolanco no problem, ¡a la orden! :wink:

**Comment by ryanoliver** [comment]
thanks for fixing this @jonahoffline

**Comment by jonahoffline** [comment]
@r23712 :wink:
