### ISSUE TITLE
Startup markets setter creating duplicates

### ISSUE THREAD

**Issue by jpadilla** [SoPR/sopr-platform#6]
Startup markets setter creating duplicates each time startup is updated.

**Comment by axelrivera** [comment]
The markets table should be removed completely and replaced with tags.  They are more appropiate and flexible for this situation.

Check out https://github.com/mbleigh/acts-as-taggable-on

**Comment by jpadilla** [comment]
@riveralabs thanks, looking to it. I'll give it a try. Support for Rails 4 is currently unreleased so I'm expecting to be broken, but we might be able to get away with it since we don't need anything fancy.

I think we only need `acts_as_ordered_taggable_on :markets` on the Startup model. What do you think?

**Comment by jpadilla** [comment]
@riveralabs success! works like a charm

**Comment by axelrivera** [comment]
Very nice!!  That's the way to go!!
