### ISSUE TITLE
Usercard issue in Safari

### ISSUE THREAD

**Issue by jonahoffline** [SoPR/sopr-platform#9]
There is a problem when rendering the usercards in Safari. 
![safari_bug](https://f.cloud.github.com/assets/1783738/877935/e4ea53fe-f900-11e2-956a-fcd9958e28dc.png)

I gave it a shot but had no luck. I'm running Safari version is 6.0.5 (8536.30.1) with Mountain Lion 10.8.4

Cheers!

**Comment by jpadilla** [comment]
This seems to be fixed in Safari 7.0 on OS X Mavericks http://d.pr/i/Gtn5. I'll try to fix this using the technique we use in Blimp.

**Comment by jonahoffline** [comment]
Awesome, it works now! :+1: :100: 
![screen shot 2013-07-31 at 2 26 03 pm](https://f.cloud.github.com/assets/1783738/888504/bfc5e6ce-fa0e-11e2-8b10-97f7a5f0fc50.png)
